#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:14.21.3

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - apt-get update && apt-get install -y rsync
            - ssh-keyscan -H $SSH_SERVER_IP >> ~/.ssh/known_hosts
            - cd $BITBUCKET_CLONE_DIR
            - rsync -r -v -e ssh . $SSH_SERVER_USER@$SSH_SERVER_IP:/home/aldeia/web/aldeiapet.com.br/aldeiapet-laravel/aldeia-vue-front --delete-before --exclude '.git'
            - ssh $SSH_SERVER_USER@$SSH_SERVER_IP 'cd /home/aldeia/web/aldeiapet.com.br/aldeiapet-laravel/aldeia-vue-front && npm update && npm install'
            - ssh $SSH_SERVER_USER@$SSH_SERVER_IP 'cd /home/aldeia/web/aldeiapet.com.br/aldeiapet-laravel/aldeia-vue-front && npm run build'
            - ssh $SSH_SERVER_USER@$SSH_SERVER_IP 'cd /home/aldeia/web/aldeiapet.com.br/aldeiapet-laravel/aldeia-vue-front && rsync -ra dist/ ../../public_html/dist'